server:
  port: 8062

spring:
  application:
    name: gateway-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system_manager_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: simple
    password: simple@321!
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      testOnBorrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20



