spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，利用微服务名进行路由
          lowerCaseServiceId: true #服务名转小写
      routes:
        - id: gateway_router
          uri: lb://gateway-service
          predicates:
            - Path=/manager/**
          filters:
            - StripPrefix=1


router:
  path: manager




